import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
  AiFillChrome,
  AiFillGithub,
  AiFillLinkedin,
  AiFillYoutube,
} from 'react-icons/ai';
import Image from 'next/image';
import lem from '../public/lem-profile.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react';
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Lem's NextJs Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-bold dark:text-white">lemdigital</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-white">
              Lemar Corales
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Developer and Designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
              Freelancer providing services for programming and design content
              needs. Join me down below and let's work together.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
              <a href="https://github.com/Lem05" target="_blank">
                <AiFillGithub />
              </a>
              <a
                href="https://www.linkedin.com/in/lemar-corales/"
                target="_blank">
                <AiFillLinkedin />
              </a>
              <a href="https://lemdigitalagency@gmail.com" target="_blank">
                <AiFillChrome />
              </a>
            </div>
            <div>
              <br />
              <a
                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 sm:text-1sm"
                href="#">
                Lets Work Together
              </a>
            </div>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={lem} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Services I Offer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-white">
              Since the beginning of my journey as a freelancer designer and
              developer, I've done remote work for{' '}
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                width={'100'}
                height={'100'}
                layout="responsive"
                src={design}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Design
              </h3>
              <p>
                Creating elegant design suited for your needs and design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I used</h4>
              <p className="text-gray-800 py-1">Canva</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Miro</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                width={'100'}
                height={'100'}
                layout="responsive"
                src={code}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Design
              </h3>
              <p>
                Creating elegant design suited for your needs and design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I used</h4>
              <p className="text-gray-800 py-1">Canva</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Miro</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                width={'100'}
                height={'100'}
                layout="responsive"
                src={consulting}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Design
              </h3>
              <p>
                Creating elegant design suited for your needs and design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I used</h4>
              <p className="text-gray-800 py-1">Canva</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Miro</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-white">
              Since the beginning of my journey as a freelancer designer and
              developer, I've done remote work for{' '}
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
